//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB10
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string city { get; set; }
        public string grade { get; set; }
        public int salesman_id { get; set; }
    
        public virtual customer customer1 { get; set; }
        public virtual customer customer2 { get; set; }
    }
}
