//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB10
{
    using System;
    using System.Collections.Generic;
    
    public partial class Q1
    {
        public int salesman_id { get; set; }
        public string salesman_name { get; set; }
        public string city { get; set; }
        public double commission { get; set; }
    }
}
