//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrSunao.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/OrSunao")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getimagelength", ReplyAction="http://tempuri.org/IService1/getimagelengthResponse")]
        int getimagelength(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getimagelength", ReplyAction="http://tempuri.org/IService1/getimagelengthResponse")]
        System.Threading.Tasks.Task<int> getimagelengthAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkimage", ReplyAction="http://tempuri.org/IService1/checkimageResponse")]
        bool checkimage(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkimage", ReplyAction="http://tempuri.org/IService1/checkimageResponse")]
        System.Threading.Tasks.Task<bool> checkimageAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setImageToEmpty", ReplyAction="http://tempuri.org/IService1/setImageToEmptyResponse")]
        void setImageToEmpty(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setImageToEmpty", ReplyAction="http://tempuri.org/IService1/setImageToEmptyResponse")]
        System.Threading.Tasks.Task setImageToEmptyAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getChatImage", ReplyAction="http://tempuri.org/IService1/getChatImageResponse")]
        OrSunao.ServiceReference1.getChatImageResponse getChatImage(OrSunao.ServiceReference1.getChatImageRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getChatImage", ReplyAction="http://tempuri.org/IService1/getChatImageResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.getChatImageResponse> getChatImageAsync(OrSunao.ServiceReference1.getChatImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setChatToImage", ReplyAction="http://tempuri.org/IService1/setChatToImageResponse")]
        void setChatToImage(string Email, byte[] img, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setChatToImage", ReplyAction="http://tempuri.org/IService1/setChatToImageResponse")]
        System.Threading.Tasks.Task setChatToImageAsync(string Email, byte[] img, int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addusertogroup", ReplyAction="http://tempuri.org/IService1/addusertogroupResponse")]
        void addusertogroup(string myemail, string hisemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addusertogroup", ReplyAction="http://tempuri.org/IService1/addusertogroupResponse")]
        System.Threading.Tasks.Task addusertogroupAsync(string myemail, string hisemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsersgroupContacts", ReplyAction="http://tempuri.org/IService1/getUsersgroupContactsResponse")]
        OrSunao.ServiceReference1.getUsersgroupContactsResponse getUsersgroupContacts(OrSunao.ServiceReference1.getUsersgroupContactsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsersgroupContacts", ReplyAction="http://tempuri.org/IService1/getUsersgroupContactsResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.getUsersgroupContactsResponse> getUsersgroupContactsAsync(OrSunao.ServiceReference1.getUsersgroupContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SIsOfflineUser", ReplyAction="http://tempuri.org/IService1/SIsOfflineUserResponse")]
        bool SIsOfflineUser(string myemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SIsOfflineUser", ReplyAction="http://tempuri.org/IService1/SIsOfflineUserResponse")]
        System.Threading.Tasks.Task<bool> SIsOfflineUserAsync(string myemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SOfflineUser", ReplyAction="http://tempuri.org/IService1/SOfflineUserResponse")]
        void SOfflineUser(string myemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SOfflineUser", ReplyAction="http://tempuri.org/IService1/SOfflineUserResponse")]
        System.Threading.Tasks.Task SOfflineUserAsync(string myemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SConnectwithuser", ReplyAction="http://tempuri.org/IService1/SConnectwithuserResponse")]
        bool SConnectwithuser(string myemail, string hisemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SConnectwithuser", ReplyAction="http://tempuri.org/IService1/SConnectwithuserResponse")]
        System.Threading.Tasks.Task<bool> SConnectwithuserAsync(string myemail, string hisemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SDeleteUser", ReplyAction="http://tempuri.org/IService1/SDeleteUserResponse")]
        bool SDeleteUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SDeleteUser", ReplyAction="http://tempuri.org/IService1/SDeleteUserResponse")]
        System.Threading.Tasks.Task<bool> SDeleteUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SSuspendUser", ReplyAction="http://tempuri.org/IService1/SSuspendUserResponse")]
        bool SSuspendUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SSuspendUser", ReplyAction="http://tempuri.org/IService1/SSuspendUserResponse")]
        System.Threading.Tasks.Task<bool> SSuspendUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsersContacts", ReplyAction="http://tempuri.org/IService1/getUsersContactsResponse")]
        OrSunao.ServiceReference1.getUsersContactsResponse getUsersContacts(OrSunao.ServiceReference1.getUsersContactsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsersContacts", ReplyAction="http://tempuri.org/IService1/getUsersContactsResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.getUsersContactsResponse> getUsersContactsAsync(OrSunao.ServiceReference1.getUsersContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassRegisteredUsersname", ReplyAction="http://tempuri.org/IService1/SPassRegisteredUsersnameResponse")]
        OrSunao.ServiceReference1.SPassRegisteredUsersnameResponse SPassRegisteredUsersname(OrSunao.ServiceReference1.SPassRegisteredUsersnameRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassRegisteredUsersname", ReplyAction="http://tempuri.org/IService1/SPassRegisteredUsersnameResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassRegisteredUsersnameResponse> SPassRegisteredUsersnameAsync(OrSunao.ServiceReference1.SPassRegisteredUsersnameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassRegisteredUserspassword", ReplyAction="http://tempuri.org/IService1/SPassRegisteredUserspasswordResponse")]
        OrSunao.ServiceReference1.SPassRegisteredUserspasswordResponse SPassRegisteredUserspassword(OrSunao.ServiceReference1.SPassRegisteredUserspasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassRegisteredUserspassword", ReplyAction="http://tempuri.org/IService1/SPassRegisteredUserspasswordResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassRegisteredUserspasswordResponse> SPassRegisteredUserspasswordAsync(OrSunao.ServiceReference1.SPassRegisteredUserspasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassSuspendedUsersname", ReplyAction="http://tempuri.org/IService1/SPassSuspendedUsersnameResponse")]
        OrSunao.ServiceReference1.SPassSuspendedUsersnameResponse SPassSuspendedUsersname(OrSunao.ServiceReference1.SPassSuspendedUsersnameRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassSuspendedUsersname", ReplyAction="http://tempuri.org/IService1/SPassSuspendedUsersnameResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassSuspendedUsersnameResponse> SPassSuspendedUsersnameAsync(OrSunao.ServiceReference1.SPassSuspendedUsersnameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassSuspendedUserspassword", ReplyAction="http://tempuri.org/IService1/SPassSuspendedUserspasswordResponse")]
        OrSunao.ServiceReference1.SPassSuspendedUserspasswordResponse SPassSuspendedUserspassword(OrSunao.ServiceReference1.SPassSuspendedUserspasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassSuspendedUserspassword", ReplyAction="http://tempuri.org/IService1/SPassSuspendedUserspasswordResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassSuspendedUserspasswordResponse> SPassSuspendedUserspasswordAsync(OrSunao.ServiceReference1.SPassSuspendedUserspasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassToBeRegisteredUsersname", ReplyAction="http://tempuri.org/IService1/SPassToBeRegisteredUsersnameResponse")]
        OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameResponse SPassToBeRegisteredUsersname(OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassToBeRegisteredUsersname", ReplyAction="http://tempuri.org/IService1/SPassToBeRegisteredUsersnameResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameResponse> SPassToBeRegisteredUsersnameAsync(OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassToBeRegisteredUserspassword", ReplyAction="http://tempuri.org/IService1/SPassToBeRegisteredUserspasswordResponse")]
        OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordResponse SPassToBeRegisteredUserspassword(OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassToBeRegisteredUserspassword", ReplyAction="http://tempuri.org/IService1/SPassToBeRegisteredUserspasswordResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordResponse> SPassToBeRegisteredUserspasswordAsync(OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SRegisterUser", ReplyAction="http://tempuri.org/IService1/SRegisterUserResponse")]
        bool SRegisterUser(string firstname, string lastname, string password, string email, string contact, string cnic, string secretq, string ans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SRegisterUser", ReplyAction="http://tempuri.org/IService1/SRegisterUserResponse")]
        System.Threading.Tasks.Task<bool> SRegisterUserAsync(string firstname, string lastname, string password, string email, string contact, string cnic, string secretq, string ans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SLoginUser", ReplyAction="http://tempuri.org/IService1/SLoginUserResponse")]
        bool SLoginUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SLoginUser", ReplyAction="http://tempuri.org/IService1/SLoginUserResponse")]
        System.Threading.Tasks.Task<bool> SLoginUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassUser", ReplyAction="http://tempuri.org/IService1/SPassUserResponse")]
        bool SPassUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SPassUser", ReplyAction="http://tempuri.org/IService1/SPassUserResponse")]
        System.Threading.Tasks.Task<bool> SPassUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        OrSunao.ServiceReference1.CompositeType GetDataUsingDataContract(OrSunao.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(OrSunao.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SRegisterAdmin", ReplyAction="http://tempuri.org/IService1/SRegisterAdminResponse")]
        bool SRegisterAdmin(string UserFirstName, string UserLastName, string Password, string Email, string CNIC, string Contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SRegisterAdmin", ReplyAction="http://tempuri.org/IService1/SRegisterAdminResponse")]
        System.Threading.Tasks.Task<bool> SRegisterAdminAsync(string UserFirstName, string UserLastName, string Password, string Email, string CNIC, string Contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SLoginAdmin", ReplyAction="http://tempuri.org/IService1/SLoginAdminResponse")]
        bool SLoginAdmin(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SLoginAdmin", ReplyAction="http://tempuri.org/IService1/SLoginAdminResponse")]
        System.Threading.Tasks.Task<bool> SLoginAdminAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeactivateMyAccount", ReplyAction="http://tempuri.org/IService1/DeactivateMyAccountResponse")]
        bool DeactivateMyAccount(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeactivateMyAccount", ReplyAction="http://tempuri.org/IService1/DeactivateMyAccountResponse")]
        System.Threading.Tasks.Task<bool> DeactivateMyAccountAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToContacts", ReplyAction="http://tempuri.org/IService1/AddToContactsResponse")]
        void AddToContacts(string myEmail, string myPassword, string hisEmail, string hisPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToContacts", ReplyAction="http://tempuri.org/IService1/AddToContactsResponse")]
        System.Threading.Tasks.Task AddToContactsAsync(string myEmail, string myPassword, string hisEmail, string hisPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToBlockedUsers", ReplyAction="http://tempuri.org/IService1/AddToBlockedUsersResponse")]
        void AddToBlockedUsers(string myEmail, string hisEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToBlockedUsers", ReplyAction="http://tempuri.org/IService1/AddToBlockedUsersResponse")]
        System.Threading.Tasks.Task AddToBlockedUsersAsync(string myEmail, string hisEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setChatToText", ReplyAction="http://tempuri.org/IService1/setChatToTextResponse")]
        void setChatToText(string Email, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setChatToText", ReplyAction="http://tempuri.org/IService1/setChatToTextResponse")]
        System.Threading.Tasks.Task setChatToTextAsync(string Email, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setChatToEmpty", ReplyAction="http://tempuri.org/IService1/setChatToEmptyResponse")]
        void setChatToEmpty(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setChatToEmpty", ReplyAction="http://tempuri.org/IService1/setChatToEmptyResponse")]
        System.Threading.Tasks.Task setChatToEmptyAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getChatText", ReplyAction="http://tempuri.org/IService1/getChatTextResponse")]
        OrSunao.ServiceReference1.getChatTextResponse getChatText(OrSunao.ServiceReference1.getChatTextRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getChatText", ReplyAction="http://tempuri.org/IService1/getChatTextResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.getChatTextResponse> getChatTextAsync(OrSunao.ServiceReference1.getChatTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isConnected", ReplyAction="http://tempuri.org/IService1/isConnectedResponse")]
        OrSunao.ServiceReference1.isConnectedResponse isConnected(OrSunao.ServiceReference1.isConnectedRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isConnected", ReplyAction="http://tempuri.org/IService1/isConnectedResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.isConnectedResponse> isConnectedAsync(OrSunao.ServiceReference1.isConnectedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setConnected", ReplyAction="http://tempuri.org/IService1/setConnectedResponse")]
        void setConnected(string Email, bool connected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setConnected", ReplyAction="http://tempuri.org/IService1/setConnectedResponse")]
        System.Threading.Tasks.Task setConnectedAsync(string Email, bool connected);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setGroupChatText", ReplyAction="http://tempuri.org/IService1/setGroupChatTextResponse")]
        void setGroupChatText(string Email, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setGroupChatText", ReplyAction="http://tempuri.org/IService1/setGroupChatTextResponse")]
        System.Threading.Tasks.Task setGroupChatTextAsync(string Email, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setGroupChatToEmpty", ReplyAction="http://tempuri.org/IService1/setGroupChatToEmptyResponse")]
        void setGroupChatToEmpty(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setGroupChatToEmpty", ReplyAction="http://tempuri.org/IService1/setGroupChatToEmptyResponse")]
        System.Threading.Tasks.Task setGroupChatToEmptyAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGroupChatText", ReplyAction="http://tempuri.org/IService1/getGroupChatTextResponse")]
        OrSunao.ServiceReference1.getGroupChatTextResponse getGroupChatText(OrSunao.ServiceReference1.getGroupChatTextRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getGroupChatText", ReplyAction="http://tempuri.org/IService1/getGroupChatTextResponse")]
        System.Threading.Tasks.Task<OrSunao.ServiceReference1.getGroupChatTextResponse> getGroupChatTextAsync(OrSunao.ServiceReference1.getGroupChatTextRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChatImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getChatImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] img;
        
        public getChatImageRequest() {
        }
        
        public getChatImageRequest(string Email, byte[] img) {
            this.Email = Email;
            this.img = img;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChatImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getChatImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] img;
        
        public getChatImageResponse() {
        }
        
        public getChatImageResponse(byte[] img) {
            this.img = img;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersgroupContacts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUsersgroupContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] str;
        
        public getUsersgroupContactsRequest() {
        }
        
        public getUsersgroupContactsRequest(string email, string[] str) {
            this.email = email;
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersgroupContactsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUsersgroupContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public getUsersgroupContactsResponse() {
        }
        
        public getUsersgroupContactsResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersContacts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUsersContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] str;
        
        public getUsersContactsRequest() {
        }
        
        public getUsersContactsRequest(string email, string[] str) {
            this.email = email;
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersContactsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getUsersContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public getUsersContactsResponse() {
        }
        
        public getUsersContactsResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassRegisteredUsersname", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassRegisteredUsersnameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassRegisteredUsersnameRequest() {
        }
        
        public SPassRegisteredUsersnameRequest(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassRegisteredUsersnameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassRegisteredUsersnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassRegisteredUsersnameResponse() {
        }
        
        public SPassRegisteredUsersnameResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassRegisteredUserspassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassRegisteredUserspasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassRegisteredUserspasswordRequest() {
        }
        
        public SPassRegisteredUserspasswordRequest(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassRegisteredUserspasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassRegisteredUserspasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassRegisteredUserspasswordResponse() {
        }
        
        public SPassRegisteredUserspasswordResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassSuspendedUsersname", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassSuspendedUsersnameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassSuspendedUsersnameRequest() {
        }
        
        public SPassSuspendedUsersnameRequest(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassSuspendedUsersnameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassSuspendedUsersnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassSuspendedUsersnameResponse() {
        }
        
        public SPassSuspendedUsersnameResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassSuspendedUserspassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassSuspendedUserspasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassSuspendedUserspasswordRequest() {
        }
        
        public SPassSuspendedUserspasswordRequest(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassSuspendedUserspasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassSuspendedUserspasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassSuspendedUserspasswordResponse() {
        }
        
        public SPassSuspendedUserspasswordResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassToBeRegisteredUsersname", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassToBeRegisteredUsersnameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassToBeRegisteredUsersnameRequest() {
        }
        
        public SPassToBeRegisteredUsersnameRequest(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassToBeRegisteredUsersnameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassToBeRegisteredUsersnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassToBeRegisteredUsersnameResponse() {
        }
        
        public SPassToBeRegisteredUsersnameResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassToBeRegisteredUserspassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassToBeRegisteredUserspasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassToBeRegisteredUserspasswordRequest() {
        }
        
        public SPassToBeRegisteredUserspasswordRequest(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SPassToBeRegisteredUserspasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SPassToBeRegisteredUserspasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public SPassToBeRegisteredUserspasswordResponse() {
        }
        
        public SPassToBeRegisteredUserspasswordResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChatText", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getChatTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string msg;
        
        public getChatTextRequest() {
        }
        
        public getChatTextRequest(string Email, string msg) {
            this.Email = Email;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getChatTextResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getChatTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msg;
        
        public getChatTextResponse() {
        }
        
        public getChatTextResponse(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isConnected", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class isConnectedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool connected;
        
        public isConnectedRequest() {
        }
        
        public isConnectedRequest(string Email, bool connected) {
            this.Email = Email;
            this.connected = connected;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isConnectedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class isConnectedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool connected;
        
        public isConnectedResponse() {
        }
        
        public isConnectedResponse(bool connected) {
            this.connected = connected;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupChatText", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getGroupChatTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] str;
        
        public getGroupChatTextRequest() {
        }
        
        public getGroupChatTextRequest(string Email, string[] str) {
            this.Email = Email;
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGroupChatTextResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getGroupChatTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] str;
        
        public getGroupChatTextResponse() {
        }
        
        public getGroupChatTextResponse(string[] str) {
            this.str = str;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OrSunao.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OrSunao.ServiceReference1.IService1>, OrSunao.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getimagelength(string email) {
            return base.Channel.getimagelength(email);
        }
        
        public System.Threading.Tasks.Task<int> getimagelengthAsync(string email) {
            return base.Channel.getimagelengthAsync(email);
        }
        
        public bool checkimage(string email) {
            return base.Channel.checkimage(email);
        }
        
        public System.Threading.Tasks.Task<bool> checkimageAsync(string email) {
            return base.Channel.checkimageAsync(email);
        }
        
        public void setImageToEmpty(string Email) {
            base.Channel.setImageToEmpty(Email);
        }
        
        public System.Threading.Tasks.Task setImageToEmptyAsync(string Email) {
            return base.Channel.setImageToEmptyAsync(Email);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.getChatImageResponse OrSunao.ServiceReference1.IService1.getChatImage(OrSunao.ServiceReference1.getChatImageRequest request) {
            return base.Channel.getChatImage(request);
        }
        
        public void getChatImage(string Email, ref byte[] img) {
            OrSunao.ServiceReference1.getChatImageRequest inValue = new OrSunao.ServiceReference1.getChatImageRequest();
            inValue.Email = Email;
            inValue.img = img;
            OrSunao.ServiceReference1.getChatImageResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).getChatImage(inValue);
            img = retVal.img;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.getChatImageResponse> getChatImageAsync(OrSunao.ServiceReference1.getChatImageRequest request) {
            return base.Channel.getChatImageAsync(request);
        }
        
        public void setChatToImage(string Email, byte[] img, int length) {
            base.Channel.setChatToImage(Email, img, length);
        }
        
        public System.Threading.Tasks.Task setChatToImageAsync(string Email, byte[] img, int length) {
            return base.Channel.setChatToImageAsync(Email, img, length);
        }
        
        public void addusertogroup(string myemail, string hisemail) {
            base.Channel.addusertogroup(myemail, hisemail);
        }
        
        public System.Threading.Tasks.Task addusertogroupAsync(string myemail, string hisemail) {
            return base.Channel.addusertogroupAsync(myemail, hisemail);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.getUsersgroupContactsResponse OrSunao.ServiceReference1.IService1.getUsersgroupContacts(OrSunao.ServiceReference1.getUsersgroupContactsRequest request) {
            return base.Channel.getUsersgroupContacts(request);
        }
        
        public void getUsersgroupContacts(string email, ref string[] str) {
            OrSunao.ServiceReference1.getUsersgroupContactsRequest inValue = new OrSunao.ServiceReference1.getUsersgroupContactsRequest();
            inValue.email = email;
            inValue.str = str;
            OrSunao.ServiceReference1.getUsersgroupContactsResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).getUsersgroupContacts(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.getUsersgroupContactsResponse> getUsersgroupContactsAsync(OrSunao.ServiceReference1.getUsersgroupContactsRequest request) {
            return base.Channel.getUsersgroupContactsAsync(request);
        }
        
        public bool SIsOfflineUser(string myemail) {
            return base.Channel.SIsOfflineUser(myemail);
        }
        
        public System.Threading.Tasks.Task<bool> SIsOfflineUserAsync(string myemail) {
            return base.Channel.SIsOfflineUserAsync(myemail);
        }
        
        public void SOfflineUser(string myemail) {
            base.Channel.SOfflineUser(myemail);
        }
        
        public System.Threading.Tasks.Task SOfflineUserAsync(string myemail) {
            return base.Channel.SOfflineUserAsync(myemail);
        }
        
        public bool SConnectwithuser(string myemail, string hisemail) {
            return base.Channel.SConnectwithuser(myemail, hisemail);
        }
        
        public System.Threading.Tasks.Task<bool> SConnectwithuserAsync(string myemail, string hisemail) {
            return base.Channel.SConnectwithuserAsync(myemail, hisemail);
        }
        
        public bool SDeleteUser(string email, string password) {
            return base.Channel.SDeleteUser(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> SDeleteUserAsync(string email, string password) {
            return base.Channel.SDeleteUserAsync(email, password);
        }
        
        public bool SSuspendUser(string email, string password) {
            return base.Channel.SSuspendUser(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> SSuspendUserAsync(string email, string password) {
            return base.Channel.SSuspendUserAsync(email, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.getUsersContactsResponse OrSunao.ServiceReference1.IService1.getUsersContacts(OrSunao.ServiceReference1.getUsersContactsRequest request) {
            return base.Channel.getUsersContacts(request);
        }
        
        public void getUsersContacts(string email, ref string[] str) {
            OrSunao.ServiceReference1.getUsersContactsRequest inValue = new OrSunao.ServiceReference1.getUsersContactsRequest();
            inValue.email = email;
            inValue.str = str;
            OrSunao.ServiceReference1.getUsersContactsResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).getUsersContacts(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.getUsersContactsResponse> getUsersContactsAsync(OrSunao.ServiceReference1.getUsersContactsRequest request) {
            return base.Channel.getUsersContactsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.SPassRegisteredUsersnameResponse OrSunao.ServiceReference1.IService1.SPassRegisteredUsersname(OrSunao.ServiceReference1.SPassRegisteredUsersnameRequest request) {
            return base.Channel.SPassRegisteredUsersname(request);
        }
        
        public void SPassRegisteredUsersname(ref string[] str) {
            OrSunao.ServiceReference1.SPassRegisteredUsersnameRequest inValue = new OrSunao.ServiceReference1.SPassRegisteredUsersnameRequest();
            inValue.str = str;
            OrSunao.ServiceReference1.SPassRegisteredUsersnameResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).SPassRegisteredUsersname(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassRegisteredUsersnameResponse> SPassRegisteredUsersnameAsync(OrSunao.ServiceReference1.SPassRegisteredUsersnameRequest request) {
            return base.Channel.SPassRegisteredUsersnameAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.SPassRegisteredUserspasswordResponse OrSunao.ServiceReference1.IService1.SPassRegisteredUserspassword(OrSunao.ServiceReference1.SPassRegisteredUserspasswordRequest request) {
            return base.Channel.SPassRegisteredUserspassword(request);
        }
        
        public void SPassRegisteredUserspassword(ref string[] str) {
            OrSunao.ServiceReference1.SPassRegisteredUserspasswordRequest inValue = new OrSunao.ServiceReference1.SPassRegisteredUserspasswordRequest();
            inValue.str = str;
            OrSunao.ServiceReference1.SPassRegisteredUserspasswordResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).SPassRegisteredUserspassword(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassRegisteredUserspasswordResponse> SPassRegisteredUserspasswordAsync(OrSunao.ServiceReference1.SPassRegisteredUserspasswordRequest request) {
            return base.Channel.SPassRegisteredUserspasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.SPassSuspendedUsersnameResponse OrSunao.ServiceReference1.IService1.SPassSuspendedUsersname(OrSunao.ServiceReference1.SPassSuspendedUsersnameRequest request) {
            return base.Channel.SPassSuspendedUsersname(request);
        }
        
        public void SPassSuspendedUsersname(ref string[] str) {
            OrSunao.ServiceReference1.SPassSuspendedUsersnameRequest inValue = new OrSunao.ServiceReference1.SPassSuspendedUsersnameRequest();
            inValue.str = str;
            OrSunao.ServiceReference1.SPassSuspendedUsersnameResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).SPassSuspendedUsersname(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassSuspendedUsersnameResponse> SPassSuspendedUsersnameAsync(OrSunao.ServiceReference1.SPassSuspendedUsersnameRequest request) {
            return base.Channel.SPassSuspendedUsersnameAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.SPassSuspendedUserspasswordResponse OrSunao.ServiceReference1.IService1.SPassSuspendedUserspassword(OrSunao.ServiceReference1.SPassSuspendedUserspasswordRequest request) {
            return base.Channel.SPassSuspendedUserspassword(request);
        }
        
        public void SPassSuspendedUserspassword(ref string[] str) {
            OrSunao.ServiceReference1.SPassSuspendedUserspasswordRequest inValue = new OrSunao.ServiceReference1.SPassSuspendedUserspasswordRequest();
            inValue.str = str;
            OrSunao.ServiceReference1.SPassSuspendedUserspasswordResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).SPassSuspendedUserspassword(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassSuspendedUserspasswordResponse> SPassSuspendedUserspasswordAsync(OrSunao.ServiceReference1.SPassSuspendedUserspasswordRequest request) {
            return base.Channel.SPassSuspendedUserspasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameResponse OrSunao.ServiceReference1.IService1.SPassToBeRegisteredUsersname(OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameRequest request) {
            return base.Channel.SPassToBeRegisteredUsersname(request);
        }
        
        public void SPassToBeRegisteredUsersname(ref string[] str) {
            OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameRequest inValue = new OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameRequest();
            inValue.str = str;
            OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).SPassToBeRegisteredUsersname(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameResponse> SPassToBeRegisteredUsersnameAsync(OrSunao.ServiceReference1.SPassToBeRegisteredUsersnameRequest request) {
            return base.Channel.SPassToBeRegisteredUsersnameAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordResponse OrSunao.ServiceReference1.IService1.SPassToBeRegisteredUserspassword(OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordRequest request) {
            return base.Channel.SPassToBeRegisteredUserspassword(request);
        }
        
        public void SPassToBeRegisteredUserspassword(ref string[] str) {
            OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordRequest inValue = new OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordRequest();
            inValue.str = str;
            OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).SPassToBeRegisteredUserspassword(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordResponse> SPassToBeRegisteredUserspasswordAsync(OrSunao.ServiceReference1.SPassToBeRegisteredUserspasswordRequest request) {
            return base.Channel.SPassToBeRegisteredUserspasswordAsync(request);
        }
        
        public bool SRegisterUser(string firstname, string lastname, string password, string email, string contact, string cnic, string secretq, string ans) {
            return base.Channel.SRegisterUser(firstname, lastname, password, email, contact, cnic, secretq, ans);
        }
        
        public System.Threading.Tasks.Task<bool> SRegisterUserAsync(string firstname, string lastname, string password, string email, string contact, string cnic, string secretq, string ans) {
            return base.Channel.SRegisterUserAsync(firstname, lastname, password, email, contact, cnic, secretq, ans);
        }
        
        public bool SLoginUser(string email, string password) {
            return base.Channel.SLoginUser(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> SLoginUserAsync(string email, string password) {
            return base.Channel.SLoginUserAsync(email, password);
        }
        
        public bool SPassUser(string email, string password) {
            return base.Channel.SPassUser(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> SPassUserAsync(string email, string password) {
            return base.Channel.SPassUserAsync(email, password);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public OrSunao.ServiceReference1.CompositeType GetDataUsingDataContract(OrSunao.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(OrSunao.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool SRegisterAdmin(string UserFirstName, string UserLastName, string Password, string Email, string CNIC, string Contact) {
            return base.Channel.SRegisterAdmin(UserFirstName, UserLastName, Password, Email, CNIC, Contact);
        }
        
        public System.Threading.Tasks.Task<bool> SRegisterAdminAsync(string UserFirstName, string UserLastName, string Password, string Email, string CNIC, string Contact) {
            return base.Channel.SRegisterAdminAsync(UserFirstName, UserLastName, Password, Email, CNIC, Contact);
        }
        
        public bool SLoginAdmin(string Email, string Password) {
            return base.Channel.SLoginAdmin(Email, Password);
        }
        
        public System.Threading.Tasks.Task<bool> SLoginAdminAsync(string Email, string Password) {
            return base.Channel.SLoginAdminAsync(Email, Password);
        }
        
        public bool DeactivateMyAccount(string email, string password) {
            return base.Channel.DeactivateMyAccount(email, password);
        }
        
        public System.Threading.Tasks.Task<bool> DeactivateMyAccountAsync(string email, string password) {
            return base.Channel.DeactivateMyAccountAsync(email, password);
        }
        
        public void AddToContacts(string myEmail, string myPassword, string hisEmail, string hisPassword) {
            base.Channel.AddToContacts(myEmail, myPassword, hisEmail, hisPassword);
        }
        
        public System.Threading.Tasks.Task AddToContactsAsync(string myEmail, string myPassword, string hisEmail, string hisPassword) {
            return base.Channel.AddToContactsAsync(myEmail, myPassword, hisEmail, hisPassword);
        }
        
        public void AddToBlockedUsers(string myEmail, string hisEmail) {
            base.Channel.AddToBlockedUsers(myEmail, hisEmail);
        }
        
        public System.Threading.Tasks.Task AddToBlockedUsersAsync(string myEmail, string hisEmail) {
            return base.Channel.AddToBlockedUsersAsync(myEmail, hisEmail);
        }
        
        public void setChatToText(string Email, string msg) {
            base.Channel.setChatToText(Email, msg);
        }
        
        public System.Threading.Tasks.Task setChatToTextAsync(string Email, string msg) {
            return base.Channel.setChatToTextAsync(Email, msg);
        }
        
        public void setChatToEmpty(string Email) {
            base.Channel.setChatToEmpty(Email);
        }
        
        public System.Threading.Tasks.Task setChatToEmptyAsync(string Email) {
            return base.Channel.setChatToEmptyAsync(Email);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.getChatTextResponse OrSunao.ServiceReference1.IService1.getChatText(OrSunao.ServiceReference1.getChatTextRequest request) {
            return base.Channel.getChatText(request);
        }
        
        public void getChatText(string Email, ref string msg) {
            OrSunao.ServiceReference1.getChatTextRequest inValue = new OrSunao.ServiceReference1.getChatTextRequest();
            inValue.Email = Email;
            inValue.msg = msg;
            OrSunao.ServiceReference1.getChatTextResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).getChatText(inValue);
            msg = retVal.msg;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.getChatTextResponse> getChatTextAsync(OrSunao.ServiceReference1.getChatTextRequest request) {
            return base.Channel.getChatTextAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.isConnectedResponse OrSunao.ServiceReference1.IService1.isConnected(OrSunao.ServiceReference1.isConnectedRequest request) {
            return base.Channel.isConnected(request);
        }
        
        public void isConnected(string Email, ref bool connected) {
            OrSunao.ServiceReference1.isConnectedRequest inValue = new OrSunao.ServiceReference1.isConnectedRequest();
            inValue.Email = Email;
            inValue.connected = connected;
            OrSunao.ServiceReference1.isConnectedResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).isConnected(inValue);
            connected = retVal.connected;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.isConnectedResponse> isConnectedAsync(OrSunao.ServiceReference1.isConnectedRequest request) {
            return base.Channel.isConnectedAsync(request);
        }
        
        public void setConnected(string Email, bool connected) {
            base.Channel.setConnected(Email, connected);
        }
        
        public System.Threading.Tasks.Task setConnectedAsync(string Email, bool connected) {
            return base.Channel.setConnectedAsync(Email, connected);
        }
        
        public void setGroupChatText(string Email, string msg) {
            base.Channel.setGroupChatText(Email, msg);
        }
        
        public System.Threading.Tasks.Task setGroupChatTextAsync(string Email, string msg) {
            return base.Channel.setGroupChatTextAsync(Email, msg);
        }
        
        public void setGroupChatToEmpty(string Email) {
            base.Channel.setGroupChatToEmpty(Email);
        }
        
        public System.Threading.Tasks.Task setGroupChatToEmptyAsync(string Email) {
            return base.Channel.setGroupChatToEmptyAsync(Email);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrSunao.ServiceReference1.getGroupChatTextResponse OrSunao.ServiceReference1.IService1.getGroupChatText(OrSunao.ServiceReference1.getGroupChatTextRequest request) {
            return base.Channel.getGroupChatText(request);
        }
        
        public void getGroupChatText(string Email, ref string[] str) {
            OrSunao.ServiceReference1.getGroupChatTextRequest inValue = new OrSunao.ServiceReference1.getGroupChatTextRequest();
            inValue.Email = Email;
            inValue.str = str;
            OrSunao.ServiceReference1.getGroupChatTextResponse retVal = ((OrSunao.ServiceReference1.IService1)(this)).getGroupChatText(inValue);
            str = retVal.str;
        }
        
        public System.Threading.Tasks.Task<OrSunao.ServiceReference1.getGroupChatTextResponse> getGroupChatTextAsync(OrSunao.ServiceReference1.getGroupChatTextRequest request) {
            return base.Channel.getGroupChatTextAsync(request);
        }
    }
}
