//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> SubTopicId { get; set; }
    
        public virtual SubTopic SubTopic { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
