name: tf1
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - imageio=2.6.1
  - ipython=7.10.1
  - ipywidgets=7.5.1
  - joblib=0.14.0
  - jupyter=1.0.0
  - matplotlib=3.1.2
  - nbdime=1.1.0
  - nltk=3.4.4
  - numexpr=2.7.0
  - numpy=1.17.3
  - pandas=0.25.3
  - pillow=6.2.1
  - pip=19.3.1
  - py-xgboost=0.90
  - pydot=1.4.1
  - pyopengl=3.1.3b2
  - python=3.7
  - python-graphviz
  - requests=2.22.0
  - scikit-image=0.16.2
  - scikit-learn=0.22
  - scipy=1.3.1
  - tqdm=4.40.0
  - tensorboard=1.15.0
  - tensorflow=1.15.0 # or tensorflow-gpu if gpu
  - tensorflow-base=1.15.0
  - tensorflow-datasets=1.2.0
  - tensorflow-estimator=1.15.1
  - tensorflow-hub=0.7.0
  - tensorflow-metadata=0.14.0
  - tensorflow-probability=0.7
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - pip:
    - atari-py==0.2.6 # on Windows, use: pip install --no-index -f https://github.com/Kojoley/atari-py/releases atari_py
    - gym==0.15.4
    - opencv-python==4.1.2.30
    - psutil==5.6.7
    - pyglet==1.3.2
    - tensorflow-serving-api==1.15.0 # or tensorflow-serving-api-gpu if gpu
    - tf-agents==0.3.0rc0
    - urlextract==0.13.0
    - tensorflow-data-validation==0.15.0 # remove if on windows
    - tensorflow-model-analysis==0.15.4 # remove if on windows
    - tensorflow-transform==0.15.0 # remove if on windows
    - tfx==0.15.0 # remove if on windows
    #- pyvirtualdisplay # add if on headless server
