//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbmAdmissions2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Block()
        {
            this.TestCenters = new HashSet<TestCenter>();
        }
    
        public int BlockId { get; set; }
        public string BlockName { get; set; }
        public int TestId { get; set; }
        public Nullable<int> RollNumberStart { get; set; }
        public Nullable<int> RollNumberEnd { get; set; }
        public string Directions { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual EntryTest EntryTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCenter> TestCenters { get; set; }
    }
}
