//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbmAdmissions2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string SettingKey { get; set; }
        public string SettingValue { get; set; }
        public string Type { get; set; }
        public string InitialValue { get; set; }
    }
}
