//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbmAdmissions2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEducation
    {
        public int Id { get; set; }
        public int EducationId { get; set; }
        public decimal Total { get; set; }
        public decimal Obtained { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> PointsType { get; set; }
        public bool IsDegreeCompleted { get; set; }
    
        public virtual EducationDetail EducationDetail { get; set; }
        public virtual Student Student { get; set; }
    }
}
