//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbmAdmissions2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProgram
    {
        public int StudentId { get; set; }
        public int ProgramId { get; set; }
        public System.DateTime DateOfApplication { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Student Student { get; set; }
    }
}
