//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbmAdmissions2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTest
    {
        public int StudentTestId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> SlotId { get; set; }
        public Nullable<int> RollNumber { get; set; }
        public int TrackingNumber { get; set; }
        public Nullable<int> ChallanFormNumber { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> Amount { get; set; }
        public string TestUser { get; set; }
        public string TestPassword { get; set; }
        public Nullable<int> TestScore { get; set; }
        public string PaymentVerifiedBy { get; set; }
        public Nullable<System.DateTime> PaymentVerifiedAt { get; set; }
        public Nullable<System.DateTime> RollNumberGeneratedAt { get; set; }
        public int TestId { get; set; }
    
        public virtual TestCenterSlot TestCenterSlot { get; set; }
        public virtual Student Student { get; set; }
    }
}
