//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbmAdmissions2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentPrograms = new HashSet<StudentProgram>();
            this.StudentTests = new HashSet<StudentTest>();
            this.StudentEducations = new HashSet<StudentEducation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string StudentCnic { get; set; }
        public string FaherCnic { get; set; }
        public string PostalAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string PhotographPath { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Religion { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string HomePhoneNo { get; set; }
        public string CellNo { get; set; }
        public int Gender { get; set; }
        public string UserId { get; set; }
        public bool IsApplicationConfirmed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual City City2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentProgram> StudentPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTest> StudentTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentEducation> StudentEducations { get; set; }
        public virtual Lookup Lookup { get; set; }
    }
}
