//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbmAdmissions2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCenterSlot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestCenterSlot()
        {
            this.StudentTests = new HashSet<StudentTest>();
        }
    
        public int SlotId { get; set; }
        public int CenterId { get; set; }
        public System.DateTime TestDateTime { get; set; }
        public Nullable<int> RollNumberStart { get; set; }
        public Nullable<int> RollNumberEnd { get; set; }
    
        public virtual TestCenter TestCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTest> StudentTests { get; set; }
    }
}
